name: Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What is the bug and how to reproduce it? (Please be brief and clear)
      placeholder: E.g., When I search for repo X, the charts don't load.
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: URL or Screenshot (Optional)
      description: The link where you found the issue, or a link to a screenshot.
    validations:
      required: false
