name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: What is your idea and why do you need it?
      placeholder: E.g., Add a pie chart to show failed vs succeeded runs visually.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions (Optional)
      description: Did you consider any other ways to solve this?
    validations:
      required: false
