import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

const SCHEMA = fs.readFileSync(path.join(__dirname, '../../pg/schema.sql'), 'utf-8');

describe('ADR-005 PostgreSQL schema identity', () => {
  it('defines all expected tables', () => {
    const tables = [
      'repos', 'runs', 'jobs', 'steps', 'pr_metrics',
      'pr_workflows', 'pr_resolution_cache', 'collection_state',
      'run_list_validators', 'test_case_stats', 'workflow_attempts', 'workflow_jobs',
      'workflow_steps', 'pr_workflow_attempts',
    ];
    for (const table of tables) {
      expect(SCHEMA).toContain(`CREATE TABLE IF NOT EXISTS ${table}`);
    }
  });

  it('uses BIGINT for GitHub run and job IDs', () => {
    expect(SCHEMA).toMatch(/runs \(.*id BIGINT PRIMARY KEY/s);
    expect(SCHEMA).toMatch(/jobs \(.*id BIGINT PRIMARY KEY/s);
  });

  it('uses GENERATED BY DEFAULT AS IDENTITY for auto-increment columns', () => {
    expect(SCHEMA).toContain('id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
  });

  it('keys run-list validators by tracked workflow and collection window', () => {
    expect(SCHEMA).toMatch(/PRIMARY KEY \(repo_id, workflow_file, window_start, window_end\)/);
  });

  it('keys workflow_attempts by run_id + run_attempt', () => {
    expect(SCHEMA).toMatch(/PRIMARY KEY \(run_id, run_attempt\)/);
  });

  it('keys workflow_jobs by run_id + run_attempt + job_id', () => {
    expect(SCHEMA).toMatch(/PRIMARY KEY \(run_id, run_attempt, job_id\)/);
  });

  it('keys workflow_steps by run_id + run_attempt + job_id + step_number', () => {
    expect(SCHEMA).toMatch(/PRIMARY KEY \(run_id, run_attempt, job_id, step_number\)/);
  });

  it('keys pr_workflow_attempts by pr_metric_id + run_id + run_attempt', () => {
    expect(SCHEMA).toMatch(/PRIMARY KEY \(pr_metric_id, run_id, run_attempt\)/);
  });

  it('enforces foreign keys for workflow_jobs -> workflow_attempts', () => {
    expect(SCHEMA).toContain('FOREIGN KEY (run_id, run_attempt) REFERENCES workflow_attempts(run_id, run_attempt) ON DELETE CASCADE');
  });

  it('enforces foreign keys for workflow_steps -> workflow_jobs', () => {
    expect(SCHEMA).toContain('FOREIGN KEY (run_id, run_attempt, job_id) REFERENCES workflow_jobs(run_id, run_attempt, job_id) ON DELETE CASCADE');
  });

  it('enforces foreign keys for pr_workflow_attempts -> workflow_attempts', () => {
    expect(SCHEMA).toMatch(/FOREIGN KEY \(run_id, run_attempt\) REFERENCES workflow_attempts\(run_id, run_attempt\) ON DELETE CASCADE/);
  });

  it('includes workflow metadata columns on runs', () => {
    expect(SCHEMA).toContain('workflow_file');
    expect(SCHEMA).toContain('workflow_ref');
    expect(SCHEMA).toContain('workflow_path');
    expect(SCHEMA).toContain('workflow_parse_status');
  });

  it('includes runner resource columns on jobs and workflow_jobs', () => {
    for (const table of ['jobs', 'workflow_jobs']) {
      expect(SCHEMA).toContain(`labels_json`);
    }
    expect(SCHEMA).toContain('resource_model');
    expect(SCHEMA).toContain('resource_count');
  });
});
